[tool.app]
name = "Recommendation-Response Tracker"
version = "1.0.0"
description = "AI-powered document analysis for tracking recommendations and responses"

[tool.models]
bert_model = "emilyalsentzer/Bio_ClinicalBERT"
llm_model = "gpt-3.5-turbo"
embedding_model = "text-embedding-ada-002"

[tool.processing]
chunk_size = 1000
chunk_overlap = 200
max_file_size_mb = 500
similarity_threshold = 0.65
max_themes_per_framework = 10

[tool.vector_store]
persist_directory = "./data/vector_store"
collection_name = "recommendations_responses"

[tool.logging]
level = "INFO"
file = "app.log"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# ===============================================
# STREAMLIT CONFIGURATION
# ===============================================

[server]
maxUploadSize = 500  # 500MB upload limit for Streamlit
maxMessageSize = 500  # 500MB message size limit
enableCORS = false
enableXsrfProtection = true
headless = false
runOnSave = false
allowRunOnSave = false
port = 8501
baseUrlPath = ""

[browser]
gatherUsageStats = false
showErrorDetails = true
serverAddress = "localhost"
serverPort = 8501

[client]
toolbarMode = "auto"
showErrorDetails = true
displayEnabled = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
enableLogging = true

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[global]
developmentMode = false
logLevel = "info"
unitTest = false
