# ===============================================
# .streamlit/config.toml
# OPTIMIZED STREAMLIT CONFIGURATION
# ===============================================

# ===============================================
# SERVER CONFIGURATION
# ===============================================
[server]
# File upload settings (CRITICAL for large files)
maxUploadSize = 500              # 500MB max upload size
maxMessageSize = 500             # 500MB max message size

# Server settings
headless = false                 # Set to true for production deployment
runOnSave = false               # Disable auto-rerun on file changes
allowRunOnSave = false          # Disable manual run on save
port = 8501                     # Default Streamlit port
baseUrlPath = ""                # Leave empty for root path

# CORS and security
enableCORS = false              # Enable if accessing from different domains
enableXsrfProtection = true     # Keep enabled for security

# Performance settings
fileWatcherType = "auto"        # File watching mechanism
enableStaticServing = true      # Enable static file serving
enableWebsocketCompression = true  # Compress WebSocket data

# ===============================================
# BROWSER CONFIGURATION
# ===============================================
[browser]
gatherUsageStats = false        # Disable usage statistics
showErrorDetails = true         # Show detailed errors (disable in production)
serverAddress = "localhost"     # Server address for browser
serverPort = 8501              # Browser connection port

# ===============================================
# CLIENT CONFIGURATION
# ===============================================
[client]
toolbarMode = "auto"           # Toolbar display mode
showErrorDetails = true        # Show client-side error details
displayEnabled = true          # Enable display
caching = true                 # Enable client-side caching

# ===============================================
# RUNNER CONFIGURATION
# ===============================================
[runner]
magicEnabled = true            # Enable Streamlit magic commands
installTracer = false          # Disable install tracing
fixMatplotlib = true          # Fix matplotlib backend
postScriptGC = true           # Enable garbage collection
fastReruns = true             # Enable fast reruns for better performance
enforceSerializableSessionState = false  # Allow non-serializable session state

# ===============================================
# LOGGER CONFIGURATION
# ===============================================
[logger]
level = "info"                # Log level (debug, info, warning, error, critical)
messageFormat = "%(asctime)s %(message)s"  # Log message format
enableLogging = true          # Enable logging

# ===============================================
# THEME CONFIGURATION
# ===============================================
[theme]
base = "light"                # Theme base (light/dark)
primaryColor = "#FF6B6B"      # Primary color for UI elements
backgroundColor = "#FFFFFF"    # Main background color
secondaryBackgroundColor = "#F0F2F6"  # Secondary background color
textColor = "#262730"         # Text color
font = "sans serif"           # Font family (sans serif, serif, monospace)

# ===============================================
# GLOBAL CONFIGURATION
# ===============================================
[global]
developmentMode = false       # Set to true for development
logLevel = "info"            # Global log level
unitTest = false             # Disable unit test mode
minCachedMessageSize = 0     # Minimum size for message caching
maxCachedMessageAge = 2      # Maximum age for cached messages (days)

# ===============================================
# DEPRECATION SETTINGS
# ===============================================
[deprecation]
showPyplotGlobalUse = false  # Hide pyplot global use warnings

# ===============================================
# UI CONFIGURATION
# ===============================================
[ui]
hideTopBar = false           # Hide top bar (set to true to hide hamburger menu)
hideSidebarNav = false       # Hide sidebar navigation
