# .streamlit/config.toml
# Streamlit configuration for DaphneAI

[server]
# Increase file upload limit to 500MB
maxUploadSize = 500
port = 8501
address = "localhost"
headless = false
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
showErrorDetails = true

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
showErrorDetails = true
toolbarMode = "minimal"
